/**
 * State Machine Constants & Flow Definitions
 */

const UserState = {
  IDLE: 'IDLE',
  WELCOME: 'WELCOME',
  DASHBOARD: 'DASHBOARD',
  SELECT_PROVIDER: 'SELECT_PROVIDER',
  SELECT_CURRENCY: 'SELECT_CURRENCY',

  // Bakong standalone flow
  BAKONG_ENTER_MERCHANT_ID: 'BAKONG_ENTER_MERCHANT_ID',
  BAKONG_ENTER_MERCHANT_NAME: 'BAKONG_ENTER_MERCHANT_NAME',
  BAKONG_ENTER_PHONE: 'BAKONG_ENTER_PHONE',

  // ABA standalone flow
  ABA_ENTER_KHR_LINK: 'ABA_ENTER_KHR_LINK',
  ABA_ENTER_USD_LINK: 'ABA_ENTER_USD_LINK',

  // Bakong + ABA dual flow
  BUNDLE_BAKONG_MERCHANT_ID: 'BUNDLE_BAKONG_MERCHANT_ID',
  BUNDLE_BAKONG_MERCHANT_NAME: 'BUNDLE_BAKONG_MERCHANT_NAME',
  BUNDLE_BAKONG_PHONE: 'BUNDLE_BAKONG_PHONE',
  BUNDLE_ABA_KHR_LINK: 'BUNDLE_ABA_KHR_LINK',
  BUNDLE_ABA_USD_LINK: 'BUNDLE_ABA_USD_LINK',

  // Confirmation screen
  CONFIRM_SUBMISSION: 'CONFIRM_SUBMISSION',

  // Self-service interactive test payment flow
  TEST_PAY_CUSTOM_AMOUNT: 'TEST_PAY_CUSTOM_AMOUNT',

  // Admin Key Wizard interactive input states
  ADMIN_INPUT_BAKONG: 'ADMIN_INPUT_BAKONG',
  ADMIN_INPUT_ABA_USD: 'ADMIN_INPUT_ABA_USD',
  ADMIN_INPUT_ABA_KHR: 'ADMIN_INPUT_ABA_KHR',
  ADMIN_INPUT_STORE_NAME: 'ADMIN_INPUT_STORE_NAME'
};

module.exports = {
  UserState
};
