services:
  - type: web
    name: paylinkapi
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"
      - key: BRAND_NAME
        value: PaylinkApi
      - key: BRAND_TAGLINE
        value: FAST • SECURE • EASY
      - key: DEFAULT_LANGUAGE
        value: km
      - key: DEFAULT_BAKONG_ACCOUNT
        value: hut_soksitchey1@aclb
      - key: DEFAULT_MERCHANT_NAME
        value: Rikidev
      - key: DEFAULT_ABA_USD_LINK
        value: https://link.payway.com.kh/ABAPAY86523639G
      - key: DEFAULT_ABA_KHR_LINK
        value: https://link.payway.com.kh/ABAPAYk8523640S
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        value: "-5393647415"
      - key: MASTER_ADMIN_ID
        value: "7283817695"
      - key: SUPPORT_USERNAME
        value: "kaixite"
      - key: SUPPORT_URL
        value: "https://t.me/kaixite"
